### ISSUE TITLE
use lower case kethereum dependencies

### ISSUE THREAD

**Issue by friedger** [uport-project/kotlin-did-jwt#24]
gradle gets confused if the two dependencies are in a gradle project:

    implementation "com.github.walleth.kethereum:wallet:$kethereum_version"
    implementation "com.github.uport-project.kotlin-did-jwt:jwt:$did_jwt_version"

due to upper case letter of KEtherum in build.gradle file.

**Comment by mirceanis** [comment]
Thanks for reporting this.
I used the camel case names to match the repository names of Komputing/KEthereum.
It seems that jitpack sees them as separate artifacts but gradle either doesn't or gets confused.
To correctly fix this we'll need to update kotlin-common and kmnid too since they also use the camel case names.

**Comment by friedger** [comment]
This is the message I get from gradle:
```
Duplicate class org.kethereum.ValuesKt found in modules model-0.75.1.jar (com.github.komputing.KEthereum:model:0.75.1) and model-0.75.1.jar (com.github.walleth.kethereum:model:0.75.1)
Duplicate class org.kethereum.crypto.ConvertersKt found in modules crypto-0.75.1.jar (com.github.komputing.KEthereum:crypto:0.75.1) and crypto-0.75.1.jar (com.github.walleth.kethereum:crypto:0.75.1)
``` 

I don't see any upper case for `kotlin-common` and `kmnid`

**Comment by mirceanis** [comment]
In kethereum 0.75 there was still some confusion about the `walleth` namespace vs `komputing`
The next version of kotlin-did-jwt should remove any reference to the `walleth` namespace.
Which version are you on?

You can try using `did_jwt_version = "29aa080e"` and `implementation "com.github.komputing.kethereum:wallet:$kethereum_version"` with the version being `kethereum_version = "0.76.1"` to check if it fixes it for you, or point to a project that's manifesting the errors so I can test on my end.

**Comment by friedger** [comment]
I still get the error with the updated version. The project is https://github.com/blockstack/app-android

**Comment by friedger** [comment]
A work around would be to use `KEtherum` in my project's depedencies.

Now, it is a question of convention: show dependencies in build.gradle be lower case only?

**Comment by mirceanis** [comment]
I did not realize this was an issue before so perhaps we should adopt this convention.
I guess this is a bigger problem on systems where files are case insensitive, so to avoid problems like that we'll keep everything lowercase here as well.

We already have a dependency refactoring in the works:
https://github.com/uport-project/kotlin-did-jwt/pull/22

Stay tuned for the next release which should ameliorate these import issues.
