### ISSUE TITLE
Use a local universal Resolver instance instead of a global object

### ISSUE THREAD

**Issue by mirceanis** [uport-project/kotlin-did-jwt#30]
This universal Resolver object would have its own resolve method which can take any did and use the correct method specific resolver.

This local Resolver instance should be used during jwt verification instead of the global.
For this to happen correctly, the already configured uni-resolver should be injected into JWTTools during construction.

This mirrors [ #167845321 ] on PT 

### Acceptance
* new `verifyJWT` method that also accepts a `Resolver`
* old method should be marked as deprecated

**Comment by ugoamanoh** [comment]
#### Development checklist

 - [x] Deprecate old verify function

 - [x] Add new verify function with resolver as param

 - [x] Change resolver in function to use local resolver

 - [ ] Update demo apps

 - [x] Add tests

**Comment by mirceanis** [comment]
This was fixed in #31
